---
- name: Create directory and file
  hosts: webserver, nfs
  remote_user: ec2-user
  become: yes
  become_user: root

  tasks:
    - name: Create directory
      file:
        path: /tmp/plays
        state: directory

    - name: Create file
      file:
        path: /tmp/plays/test
        state: touch
